blank_issues_enabled: true
contact_links:
 - name: Bug Report Guidelines ğŸŒ
   url: https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
   about: Link to help you write a good bug report.
 - name: Feature Request Guidelines ğŸŒ
   url: https://github.com/rstudio/rstudio/wiki/Writing-Good-Feature-Requests
   about: Link to help you write a good feature request.
